from setuptools import setup, find_packages

setup(
    name="csm_streaming",
    version="0.1.0",
    author="Garwil",
    author_email="oliver.garwil@gmail.com",
    description="A streaming AI companion with VAD, RAG, and LLM integration.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/200bg/csm-streaming",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "vllm==0.8.0",
        "torch==2.6.0",
        "torchaudio==2.6.0",
        "torchvision==0.21.0",
        "tokenizers==0.21.0",
        "transformers==4.49.0",
        "huggingface_hub==0.28.1",
        "moshi==0.2.2",
        "sounddevice",
        "torchtune==0.4.0",
        "torchao==0.9.0",
        "bitsandbytes",
        "peft",
        "wandb",
        "silero_vad",
        "python-multipart>=0.0.6",
        "aiofiles>=23.1.0",
        "sentence-transformers>=2.2.2",
        "ctransformers>=0.2.24",
        "sqlalchemy>=2.0.0",
        "pydantic>=2.0.0",
        "fastapi>=0.95.0",
        "uvicorn>=0.22.0",
        "websockets>=11.0.3",
        "jinja2>=3.0.0",
        "speechbrain>=0.5.15",
        "matplotlib",
        "whisper-openai",
        "silentcipher @ git+https://github.com/SesameAILabs/silentcipher@master",
        "numpy==1.26.0",
        "safetensors",
        "typing-extensions",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
